### ISSUE TITLE
OSX not building on Python 2.7

### ISSUE THREAD

**Issue by rolyp** [alan-turing-institute/esig#23]
Can’t build for Python 2.7.10 or 3.4.8 on my Mac or on the GitHub `macos-10.15` virtual machine. Installation fails with compilation error, apparently because of wrong version of SSL library.

- [x] remove `sdist` step and use of `pyenv`
  - [x] verify unnecessary
  - `[Errno 63] File name too long` (circular file path?)
    - [x] try `pip wheel` from `esig` and `esig/build`
  - [x] new build script for 2.7 only initially
    - [x] use `virtualenv` directly without `pyenv`
    - [x] remove virtual environment after use
  - [x] new GitHub job without 3.5 installation step in `build-OSX-python-2.7.yml`
  - [x] extract `$p` from `python –version` so will work with 3.4 too
  - [x] consolidate temporary folder structure
  - new GitHub job to run 2.7 build script in a Python 3.4 environment ❌ (3.4 not supported)
- experiment with dropping `pyenv`:
  - [x] with Python 2.7, run `python -m pip install -U pip virtualenv` 
    - fails with `ERROR:root:code for hash md5 was not found.`, probably to do with my `openssl` shenanigans:
      - [x] `brew reinstall python@2`
        - `FormulaUnavailableError: No available formula with the name “/usr/local/opt/python@2/.brew/python@2.rb”`
          - [x] save [`python@2.rb`](https://raw.githubusercontent.com/Homebrew/homebrew-core/94d572a132a63651739fef1931f540404b7eaa31/Formula/python%402.rb) locally then `brew reinstall python@2.rb`
- Anaconda experiment to have multiple Python versions without requiring `pyenv`, at least for 2.7 and 3.4:
  - [x] install Anaconda for Python 3.7
  - [x] install Python 2.7 virtual environment
  - [x] install Python 3.4 virtual environment
    - `PackagesNotFoundError: The following packages are not available from current channels: python=3.4.8`
      - [x] [`conda create -n myenv python=3.4 -c conda-forge`](https://stackoverflow.com/questions/56850972/why-conda-cannot-create-environment-with-python-3-4-installed-in-it)
  - run wheel build in Python 3.4 virtual environment ❌ 
    - `RuntimeError: Python 3.5 or later is required`
  - run wheel build in Python 3.5 virtual environment ❌ 
    - `fatal error: ‘string’ file not found:  #include <string>`
      - [x] set `CPATH=/Users/rperera/anaconda3/envs/py35/include/c++/v1/` before wheel build
    - `ld: warning: directory not found for option ‘-L/opt/local/lib/’;  ld: library not found for -lstdc++`
    - [x] give up for now and uninstall (seemed to be breaking `pyenv install`)
- <s>discuss [PyPI download statistics](https://pypistats.org/packages/esig) with Terry</s>
- [x] ask Peter to try building 2.7.10 and 3.4.8
- [x] fail build if any Python installation fails
- [x] temporarily enable OXS build on `mac-build` branch only
- <s>enable SSH access to GitHub Actions build</s> – haven’t needed it yet
- compilation error `_ssl.c:684:35: error: incomplete definition of type ‘struct X509_name_entry_st’` (same error with Python 2.7 and 3.4) :x:
  - experiment to force Python 2.7 build to use [libressl-2.2.7] :x:(https://www.bountysource.com/issues/47297948-error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib)
    - [x] put `libressl-2.2.7` somewhere local using `curl -O https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.7.tar.gz` then `tar xvf libressl-2.2.7.tar.gz`
    - [x] try setting `CFLAGS` include dir to `libressl-2.2.7` - failed, argument not passed to clang, [this code](https://github.com/pyenv/pyenv/issues/839#issuecomment-473489506) which ignores `CFLAGS` is probably relevant, also [homebrew bumped `openssl` from 1.0 to 1.1](https://github.com/kelaberetiv/TagUI/issues/635) on 27 Nov 2019 
    - [x] try `ln -s ~/Repo/esig/build/OSX/libressl-2.2.7 /usr/local/opt/openssl@1.1` - seems to unstick compiler but fails with linker error `ld: library not found for -lssl`
    - [x] copy `/usr/local/opt/openssl@1.1/lib/*` to `libressl-2.2.7/lib` - seems to unstick that link step, but fails with another linker error `ld: framework not found QuickTime` (and also highly dubious!)
    - [x] improve slightly by instead trying `ln -s ~/Repo/esig/build/OSX/libressl-2.2.7/include /usr/local/opt/openssl@1.1/include` (linking include dir only) - should reproduce QT error
    - apparently [--no-opencv](https://github.com/panda3d/panda3d/issues/412) will drop the QT requirement but not sure what this needs to be passed to :x: – no need to continue this inquiry as no longer trying to build 2.7 from sources
    - [install QuickTime and symlink into XCode installation](https://forum.mythtv.org/viewtopic.php?f=26&t=2966) :x: – still apparently can’t find `Quicktime.framework`
  - [x] experiment with force-removing `openssl` - later problem with [ImportError: No module named zipp](https://github.com/pypa/virtualenv/issues/1630)
  - [x] experiment with [PYTHON_CONFIGURE_OPTS=”--with-openssl-dir=./libressl-2.2.7”](https://stackoverflow.com/questions/34833791/pyenv-not-building-with-the-openssl-specified-in-cflags-lflags)
  - <s>set `brew` installations to specific versions</s> - probably possible by pointing to specific `.rb` files but prob unnecessary
  - [x] upgrade `pyenv-virtualenv` to 1.1.5 <s>fails because openssl not symlinked??</s>
  - [x] remove `anaconda` installation so `openssl` isn’t picked up from there
    - removing `anaconda` means Python falls back to default 2.7 installation that comes with MacOS, and `pip` fails with `ERROR:root:code for hash md5 was not found`
    - reinstall system-level Python 3:
      - [x] requires `xcode-select –install` (thought I already did that?)
      - [x] `brew install python3`
- [x] try with Python 2.7.1 and 2.7.17 - still fails
